//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    public partial class Doctor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Doctor()
        {
            this.DoctorPatientMatches = new HashSet<DoctorPatientMatch>();
            this.Surveys = new HashSet<Survey>();
        }

        public int DoctorID { get; set; }
        public string DoctorFName { get; set; }
        public string DoctorSName { get; set; }
        [DisplayName("Email:")]
        [Required(ErrorMessage = "This field is required!")]
        public string DoctorEmail { get; set; }
        [DisplayName("Password:")]
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "This field is required!")]
        public string DoctorPass { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DoctorPatientMatch> DoctorPatientMatches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Survey> Surveys { get; set; }

        public string LoginErrorMessage { get; set; }
    }
}
