//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientSurveyAnswer
    {
        public int PatientSurveyAnswerID { get; set; }
        public int PatientID { get; set; }
        public int QuestionID { get; set; }
        public int QuestionAnswerID { get; set; }
        public string PatientSurveyAnswer1 { get; set; }
        public System.DateTime TimeStarted { get; set; }
        public System.DateTime TimeSubmitted { get; set; }
    
        public virtual Patient Patient { get; set; }
        public virtual Question Question { get; set; }
        public virtual QuestionAnswer QuestionAnswer { get; set; }
    }
}
