//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Patient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Patient()
        {
            this.Conditions = new HashSet<Condition>();
            this.DoctorPatientMatches = new HashSet<DoctorPatientMatch>();
            this.PatientSurveyAnswers = new HashSet<PatientSurveyAnswer>();
            this.Surveys = new HashSet<Survey>();
        }

        public int PatientID { get; set; }
        public string PatientFName { get; set; }
        public string PatientSName { get; set; }
        [DisplayName("Email:")]
        [Required(ErrorMessage = "This field is required!")]
        public string PatientEmail { get; set; }
        public string PatientLoginCode { get; set; }
        [DisplayName("Password:")]
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "This field is required!")]
        public string PatientPass { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Condition> Conditions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DoctorPatientMatch> DoctorPatientMatches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientSurveyAnswer> PatientSurveyAnswers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Survey> Surveys { get; set; }

        public string LoginErrorMessage { get; set; }
    }
}
